### ISSUE TITLE
I can't open league chrome

### ISSUE THREAD

**Issue by Clubserg** [bonepl/ChromaLeague#105]
I just bpught my ornata V2 and i cant open it, i leave the log here:
15:57:46 [INFO] Started Chroma League, waiting for a game - press ENTER to exit
15:57:46 [SEVERE] Error while executing SDK Http request
javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:369)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1498)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1404)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.bonepl.razersdk.sdk.SdkRequestExecutor.execute(SdkRequestExecutor.java:31)
	at com.bonepl.razersdk.sdk.SdkRequestExecutor.executeRequest(SdkRequestExecutor.java:23)
	at com.bonepl.razersdk.SdkConnectivityChecker.versionInfo(SdkConnectivityChecker.java:25)
	at com.bonepl.razersdk.SdkConnectivityChecker.checkSdkConnectivity(SdkConnectivityChecker.java:19)
	at com.bonepl.chromaleague.tasks.SdkConnectivityCheckTask.run(SdkConnectivityCheckTask.java:9)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	Suppressed: java.net.SocketException: Connection reset by peer
		at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
		at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
		at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
		at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:400)
		... 29 more
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 26 more

15:57:46 [INFO] Running ChromaLeague version 1.1.3
15:57:46 [INFO] Your ChromaLeague version is up to date!

**Comment by bonepl** [comment]
Hi, can you share the output for the following link?
https://chromasdk.io:54236/razer/chromasdk

**Comment by Clubserg** [comment]
> Hi, can you share the output for the following link?
> https://chromasdk.io:54236/razer/chromasdk

when i open the link it doesn't work, i can't acces the web, im in spain, maybe i should try woth a VPN to check if it works?

**Comment by bonepl** [comment]
This address should be available locally after the installation of Synapse. If you can't reach it locally then is either the problem of Synapse installation or internet problem.

Please go on and try running CL on VPN.

**Comment by Clubserg** [comment]
i cannot open it even on a VPN, should i try re-installing razer drivers?

**Comment by bonepl** [comment]
Please verify that you have **Razer Chroma SDK Server** running in windows services.
You can open those with Windows + R and type services.msc

**Comment by Clubserg** [comment]
Yeah i have it, maybe i should try re-installing the razer synapse program or drivers

**Comment by bonepl** [comment]
Yeah, try removing synapse 3 completely and then install it again. Preferably with PC restart after uninstall.
