### ISSUE TITLE
Handshake issue.

### ISSUE THREAD

**Issue by GrimsGift** [bonepl/ChromaLeague#109]
Unsure of what to do :/

19:28:24 [INFO] Started Chroma League, waiting for a game - press ENTER to exit
19:28:24 [SEVERE] Error while executing SDK Http request
javax.net.ssl.SSLHandshakeException: The server selected protocol version TLS10
is not accepted by client preferences [TLS13, TLS12]
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:356)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:312)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:303)
        at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHe
llo(ServerHello.java:975)
        at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(Se
rverHello.java:897)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396
)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext
.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext
.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext
.java:199)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)

        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:14
98)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocke
tImpl.java:1404)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl
.java:441)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl
.java:412)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSock
et(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSL
ConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
ntExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
:186)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java
:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:108)
        at com.bonepl.razersdk.sdk.SdkRequestExecutor.execute(SdkRequestExecutor
.java:31)
        at com.bonepl.razersdk.sdk.SdkRequestExecutor.executeRequest(SdkRequestE
xecutor.java:23)
        at com.bonepl.razersdk.SdkConnectivityChecker.versionInfo(SdkConnectivit
yChecker.java:25)
        at com.bonepl.razersdk.SdkConnectivityChecker.checkSdkConnectivity(SdkCo
nnectivityChecker.java:19)
        at com.bonepl.chromaleague.tasks.SdkConnectivityCheckTask.run(SdkConnect
ivityCheckTask.java:9)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executo
rs.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledF
utureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

19:28:25 [INFO] Running ChromaLeague version 1.1.3
19:28:25 [INFO] Your ChromaLeague version is up to date!

**Comment by bonepl** [comment]
Hi, are you running latest Synapse?
Can you share what does the page [https://chromasdk.io:54236/razer/chromasdk](https://chromasdk.io:54236/razer/chromasdk) show?

**Comment by bonepl** [comment]
Hey man, can you try if this version of ChromaLeague works for you?
[https://mega.nz/file/DsAyiZLA#OCsD4gvvvOMo2ONt2rGXkuIvlZfnD8Ps6p1yGts6-v8](https://mega.nz/file/DsAyiZLA#OCsD4gvvvOMo2ONt2rGXkuIvlZfnD8Ps6p1yGts6-v8)
