### ISSUE TITLE
Error when League match starts

### ISSUE THREAD

**Issue by Nandop2000** [bonepl/ChromaLeague#93]
Everything seems to work fine until the match starts loading. I have Razer synapse 3.0 installed ( I have a razer Ornata).

13:31:49 [SEVERE] Error while executing SDK Http request
java.net.UnknownHostException: No such host is known (chromasdk.io)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.bonepl.razersdk.ChromaRestSDK.execute(ChromaRestSDK.java:172)
        at com.bonepl.razersdk.ChromaRestSDK.executeRequest(ChromaRestSDK.java:164)
        at com.bonepl.razersdk.ChromaRestSDK.printVersionInfo(ChromaRestSDK.java:138)
        at com.bonepl.razersdk.ChromaRestSDK.<init>(ChromaRestSDK.java:70)
        at com.bonepl.chromaleague.tasks.MainThreads.<init>(MainThreads.java:28)
        at com.bonepl.chromaleague.tasks.MainTask.run(MainTask.java:23)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

13:31:49 [SEVERE] Exception in MainTask
java.lang.IllegalStateException: java.net.UnknownHostException: No such host is known (chromasdk.io)
        at com.bonepl.razersdk.ChromaRestSDK.executeRequest(ChromaRestSDK.java:167)
        at com.bonepl.razersdk.ChromaRestSDK.printVersionInfo(ChromaRestSDK.java:138)
        at com.bonepl.razersdk.ChromaRestSDK.<init>(ChromaRestSDK.java:70)
        at com.bonepl.chromaleague.tasks.MainThreads.<init>(MainThreads.java:28)
        at com.bonepl.chromaleague.tasks.MainTask.run(MainTask.java:23)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.UnknownHostException: No such host is known (chromasdk.io)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.bonepl.razersdk.ChromaRestSDK.execute(ChromaRestSDK.java:172)
        at com.bonepl.razersdk.ChromaRestSDK.executeRequest(ChromaRestSDK.java:164)
        ... 10 more

**Comment by bonepl** [comment]
Hello, can you check in Windows services that 'Razer Chroma SDK Server' is up and running?
I experienced this once, and full removal and then installation of fresh version of Synapse 3.0 worked.

**Comment by Nandop2000** [comment]
Yes I checked if the server was running by using the code in power she'll and it said it was running.
I just installed synapse 3.0 but I could try to install it again.

**Comment by bonepl** [comment]
Can you check what is returned when you visit
https://chromasdk.io:54236/razer/chromasdk
or 
http://localhost:54235/razer/chromasdk
in your browser?

**Comment by Nandop2000** [comment]
Yes I will take a look tomorrow. Thanks for helping

**Comment by Nandop2000** [comment]
the first link returns this:
Deze site is niet bereikbaarCheck of chromasdk.io een typfout bevat.
Als de spelling klopt, voer je een Windows-netwerkcontrole uit.
DNS_PROBE_FINISHED_NXDOMAIN

the second link returns indeed this
{"core":"3.19.01","device":"3.19.01","version":"3.19.01"}

**Comment by Nandop2000** [comment]
I'm sorry that was Dutch. It meant:
This site cannot be reached Check if chromasdk.io contains a typo. If the spelling is correct, run a Windows network check. DNS_PROBE_FINISHED_NXDOMAIN

**Comment by bonepl** [comment]
This is very strange as it looks like it can't resolve chroma sdk https address through DNS, but it should as this is local address - do you have any proxy, vpn, firewall, antivirus or modified hosts file? Have you tried turning them off and trying again?

You can also try running this windows diagnostics (but they almost never work) and try to do a full reinstall of all Razer software.

**Comment by Nandop2000** [comment]
I have fixed it. It was a DNS problem.  "Protocol Version 4 (TCP/IPv4): Use the following DNS server address" was somehow empty. 
I filled it in and it works now :)
Thanks for the help

**Comment by bonepl** [comment]
Glad it works!
